# Site Info
title: Seongcheol Baek
tagline: ''
description: 'More information can be found <a href="https://www.facebook.com/s.baek0516" target="_blank">here</a>.'
baseurl: ""
url: https://arcwolf.github.io
logo: '/public/logo_arcwolf.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: arcwolf
  fullname: Seongcheol Baek
  description: An adventurous <strong>researcher</strong> in <strong>electrical network & dynamics</strong>.
  gravatar: 032095fc3e830d467fd325b4e27e814f # md5 hash of your email address
  contact:
    facebook:  https://www.facebook.com/s.baek0516
    linkedin:  https://www.linkedin.com/in/seongcheol-baek-482aa2179/
    github:    https://github.com/arcwolf
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    instagram: https://www.instagram.com/baeks2ng/
    email: mailto:7whitedays@gmail.com
    # orcid: https://orcid.org/0000-0002-3480-7588
    # linkedin: https://linkedin.com/in/seongcheol-baek-482aa2179

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  About:
    - '/about/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Github Project: 
    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

arcwolf:
  image: /public/img/profile210627.jpeg
  caption: At Kamogawa river of Kyoto, Japan in May 19, 2015.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'S_Baek' # leave blank if you don't want disqus

