# Site Info
title: Seongcheol Baek
# tagline: 'Profile Page'
description: 'More information can be found <a href="https://www.facebook.com/s.baek0516" target="_blank">here</a>.'
baseurl: ""
url: https://arcwolf.github.io
# logo: '/public/logo_myname.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: arcwolf
  fullname: Seongcheol Baek
  description: Practice makes perfect
  gravatar: 032095fc3e830d467fd325b4e27e814f # md5 hash of your email address
  contact:
    facebook:  https://www.facebook.com/s.baek0516
    linkedin:  https://www.linkedin.com/in/arcwolf/
    github:    https://github.com/arcwolf
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    instagram: https://www.instagram.com/baeks2ng/
    email: mailto:7whitedays@gmail.com
    # orcid: https://orcid.org/0000-0002-3480-7588
    # linkedin: https://linkedin.com/in/seongcheol-baek-482aa2179

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  About:
    - '/about/'
  Project:
    - '/project/'
  Playground:
    - '/playground/'
  Trip:
    - '/trip/'
  # Blog:           
  #   - '/blog/'
  #   - { Categories: '/blog/categories/' }
  #   - { Tags: '/blog/tags/' }

nav_others:
  Brunch Story (Blog):
    - 'https://brunch.co.kr/@8ea6582f25ed4a1#articles'
  Github Team: 
    - 'https://github.com/hhashbrown'

nav_ex:
  LGE: 
    - 'https://www.lg.com/us/business'
  LGE_ES:
    - 'https://www.lgnewsroom.com/about/about-lg/'
  ESL:
    - 'https://powersys.postech.ac.kr/eslab/index.do'
  POSTECH:
    - 'https://www.postech.ac.kr/eng/'
  Hikihara_LAB:
    - 'https://www-lab23.kuee.kyoto-u.ac.jp/ja/'
  Rutilea:
    - 'https://www.rutilea.com/en'
  GoogleScholar:
    - 'https://scholar.google.co.jp/citations?user=ue-Lw48AAAAJ&hl=en'
  orcid:
    - 'https://orcid.org/0000-0002-3480-7588'
  linkedin:
    - 'https://www.linkedin.com/in/seongcheol-baek-482aa2179/'
  webofscience:
    - 'https://www.webofscience.com/wos/author/record/AGJ-1585-2022'
  paper_phd:
    - 'https://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/263664'
  epson_scholarship:
    - 'https://www.epson-kokusaisyogaku.jp/'
  KJ_Joint_scholarship:
    - 'https://www.niied.go.kr/web/main/nid/niied_photo/4110'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# hero:
#   image: /public/img/we_will_be_giants_by_yalestewart.jpg
#   caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# arcwolf:
#   image: /public/img/profile210627.jpeg
#   caption: At Kamogawa river of Kyoto, Japan in May 19, 2015.

arcwolf:
  image: /public/img/profile_main20260222.JPG
  caption: At my place of Busan, South Korea, in January 22, 2025.
  # caption: At my workplace of Pohang, South Korea in July 20, 2022.

figs:
  ieeeaccess2024_1: /public/img/Fig+IEEE_Access+Security-constrained_P2P_Energy_Trading+Overall_Schematic_Diagram.png
  ieeeaccess2024_2: /public/img/Fig+IEEE_Access+Security-constrained_P2P_Energy_Trading+Casestudy3.svg
  nolta2021_1: /public/img/Fig+Nolta+Decentralized_algorithms_for_consensus-based_power_packet_distribution+Overall_Concept.svg
  nolta2021_2: /public/img/Fig+Nolta+Decentralized_algorithms_for_consensus-based_power_packet_distribution+multirouting_bu_td_v20201023.svg
  aipchaos2019_1: /public/img/Fig+AIPChaos+Consensus-based_distribution_of_power_packets_and_decentralized_control_for_routing+Ring_Network.svg
  aipchaos2019_2: /public/img/Fig+AIPChaos+Consensus-based_distribution_of_power_packets_and_decentralized_control_for_routing+Ring_Network_unbiased_n_biased_result4.svg
  project_web_dev_frontpage: /public/img/Fig+Project+Web_Dev+Frontpage.png
  project_web_dev_wbs: /public/img/Fig+Project+Web_Dev+WBS.jpg
  project_web_dev_frontpage: /public/img/Fig+Project+Web_Dev+Frontpage.png
  project_prgm_dev_distcomp_idea: /public/img/Fig+Project+Prgm_Dev+Distributed_Computation.jpg
  project_prgm_dev_concept: /public/img/Fig+Project+Prgm_Dev+Concept.png
  project_alg_planar_matching: /public/img/Fig+Project+Alg+Planar_Matching.gif
  project_exp_wbg_research: /public/img/Fig+Project+Exp+WBG_research.png
  project_exp_presentation_gan_0: /public/img/Fig+Project+Exp+Presentation_GAN_0.png
  project_exp_presentation_gan_1: /public/img/Fig+Project+Exp+Presentation_GAN_1.png
  project_exp_presentation_gan_2: /public/img/Fig+Project+Exp+Presentation_GAN_2.png
  project_exp_presentation_back_projection_problem_0: /public/img/Fig+Project+Exp+Presentation_Back-Projection_Problem_0.png
  project_exp_presentation_back_projection_problem_1: /public/img/Fig+Project+Exp+Presentation_Back-Projection_Problem_1.png
  project_exp_presentation_back_projection_problem_2: /public/img/Fig+Project+Exp+Presentation_Back-Projection_Problem_2.png
  project_exp_presentation_back_projection_problem_3: /public/img/Fig+Project+Exp+Presentation_Back-Projection_Problem_3.png
  project_recordings_session_practice_1: /public/img/Fig+Project+Recordings+Session_Practice_1.jpg
  project_recordings_live_leaflet_2: /public/img/Fig+Project+Recordings+Live_leaflet_2.jpg
  project_recordings_live_on_stage_1: /public/img/Fig+Project+Recordings+Live_on_stage_1.jpg
  project_recordings_live_on_stage_2: /public/img/Fig+Project+Recordings+Live_on_stage_2.jpg
  project_recordings_shopping_1: /public/img/Fig+Project+Recordings+Shopping_1.jpg
  project_recordings_shopping_2: /public/img/Fig+Project+Recordings+Shopping_2.jpg
  project_recordings_shopping_3: /public/img/Fig+Project+Recordings+Shopping_3.jpg
  project_recordings_new_guitar_1: /public/img/Fig+Project+Recordings+New_Guitar_1.jpg
  project_recordings_new_guitar_2: /public/img/Fig+Project+Recordings+New_Guitar_2.jpg
  project_recordings_new_gear_bluesky: /public/img/Fig+Project+Recordings+New_Gear_bluesky.jpg
  project_recordings_new_gear_midi_keyboard: /public/img/Fig+Project+Recordings+New_Gear_MIDI_keyboard.jpg
  project_recordings_guitar_play_1: /public/img/Fig+Project+Recordings+Guitar_Play_1.jpg


# Puglins
mathjax: true # whether support mathjax
# google_analytics_token: 'ya29.c.Kp4BBQiiUKl001PKf3vnZkJqZ9D3HPQXKV0BEUpEmZ5bhvcM-LfAHgH_lcJ7tA02SJ68-BnlQovtYlQxv4vTjlfRshNnQOFQ7dBP2tmS7C5Hp08OAeprfCjm1NYgOJ9lcO0_UUbUGMMO9NSFnVdjOKrGhgDD4hkBjfspT7OySDypWnZcIQ9egvU7lT_FbvM5FV8YLkuUYy1S4noqEB0ZdUc' # leave blank if you don't want google analytics
disqus_short_name: 'S_Baek' # leave blank if you don't want disqus

# Google Analytics
google_analytics: G-QNR0GYSBLW
