# Site Info
title: Seongcheol Baek
# tagline: 'Profile Page'
description: 'More information can be found <a href="https://www.facebook.com/s.baek0516" target="_blank">here</a>.'
baseurl: ""
url: https://arcwolf.github.io
# logo: '/public/logo_myname.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: arcwolf
  fullname: Seongcheol Baek
  description: Practice makes perfect
  gravatar: 032095fc3e830d467fd325b4e27e814f # md5 hash of your email address
  contact:
    facebook:  https://www.facebook.com/s.baek0516
    linkedin:  https://www.linkedin.com/in/arcwolf/
    github:    https://github.com/arcwolf
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    instagram: https://www.instagram.com/baeks2ng/
    email: mailto:7whitedays@gmail.com
    # orcid: https://orcid.org/0000-0002-3480-7588
    # linkedin: https://linkedin.com/in/seongcheol-baek-482aa2179

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  About:
    - '/about/'
  # Blog:           
  #   - '/blog/'
  #   - { Categories: '/blog/categories/' }
  #   - { Tags: '/blog/tags/' }

nav_others:
  Brunch Story (Blog):
    - 'https://brunch.co.kr/@8ea6582f25ed4a1#articles'
  Github Team: 
    - 'https://github.com/hhashbrown'

nav_ex:
  LGE: 
    - 'https://www.lg.com/us/business'
  LGE_ES:
    - 'https://www.lgnewsroom.com/about/about-lg/'
  ESL:
    - 'https://sites.google.com/view/youngjinkim/home'
  POSTECH:
    - 'https://www.postech.ac.kr/eng/'
  GoogleScholar:
    - 'https://scholar.google.co.jp/citations?user=ue-Lw48AAAAJ&hl=en'
  orcid:
    - 'https://orcid.org/0000-0002-3480-7588'
  linkedin:
    - 'https://www.linkedin.com/in/seongcheol-baek-482aa2179/'
  webofscience:
    - 'https://www.webofscience.com/wos/author/record/AGJ-1585-2022'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# hero:
#   image: /public/img/we_will_be_giants_by_yalestewart.jpg
#   caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# arcwolf:
#   image: /public/img/profile210627.jpeg
#   caption: At Kamogawa river of Kyoto, Japan in May 19, 2015.

arcwolf:
  image: /public/img/profile_main20250209.JPG
  caption: At my place of Busan, South Korea, in January 22, 2025.
  # caption: At my workplace of Pohang, South Korea in July 20, 2022.

# Puglins
mathjax: true # whether support mathjax
# google_analytics_token: 'ya29.c.Kp4BBQiiUKl001PKf3vnZkJqZ9D3HPQXKV0BEUpEmZ5bhvcM-LfAHgH_lcJ7tA02SJ68-BnlQovtYlQxv4vTjlfRshNnQOFQ7dBP2tmS7C5Hp08OAeprfCjm1NYgOJ9lcO0_UUbUGMMO9NSFnVdjOKrGhgDD4hkBjfspT7OySDypWnZcIQ9egvU7lT_FbvM5FV8YLkuUYy1S4noqEB0ZdUc' # leave blank if you don't want google analytics
disqus_short_name: 'S_Baek' # leave blank if you don't want disqus

# Google Analytics
google_analytics: G-QNR0GYSBLW
